#!/usr/bin/env bash
cat <<EOT
STABLE_KUBERNETESIMAL_CONTAINER_REGISTRY ${KUBERNETESIMAL_CONTAINER_REGISTRY:-ghcr.io}
STABLE_KUBERNETESIMAL_CONTAINER_REPOSITORY ${KUBERNETESIMAL_CONTAINER_REPOSITORY:-kkohtaka/kubernetesimal/kubernetesimal}
STABLE_KUBERNETESIMAL_CONTAINER_TAG ${KUBERNETESIMAL_CONTAINER_TAG:-latest}
EOT
