
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kubernetesimal-kkohtaka-org-v1alpha1-etcd
  failurePolicy: Fail
  name: metcd.kb.io
  rules:
  - apiGroups:
    - kubernetesimal.kkohtaka.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - etcds
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kubernetesimal-kkohtaka-org-v1alpha1-etcd
  failurePolicy: Fail
  name: vetcd.kb.io
  rules:
  - apiGroups:
    - kubernetesimal.kkohtaka.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - etcds
  sideEffects: None
