# permissions for end users to edit etcdnodesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdnodeset-editor-role
rules:
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodesets/status
  verbs:
  - get
