# permissions for end users to edit etcdnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: etcdnode-editor-role
rules:
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodes/status
  verbs:
  - get
