# permissions for end users to edit kubernetesimalconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetesimalconfig-editor-role
rules:
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - kubernetesimalconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
