
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodes/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcdnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcds/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetesimal.kkohtaka.org
  resources:
  - etcds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
