/*
Copyright 2019 Kazumasa Kohtaka <kkohtaka@gmail.com>.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path"
	"strings"

	"github.com/iancoleman/strcase"
)

func main() {
	const nArgs = 2
	if len(os.Args) < nArgs {
		log.Fatalf("%s should be called with %d arguments.\n", os.Args[0], nArgs)
	}

	inputDirName := os.Args[1]
	outputFileName := fmt.Sprintf("zz_generated.%s.go", path.Base(inputDirName))
	packageName := os.Args[2]

	inputs, err := ioutil.ReadDir(inputDirName)
	if err != nil {
		log.Fatalf("Failed to read input files in directory: %s, %v\n", inputDirName, err)
	}
	output, err := os.Create(outputFileName)
	if err != nil {
		log.Fatalf("Failed to create an output file: %s, %v\n", outputFileName, err)
	}

	output.Write([]byte(fmt.Sprintf(`// +build !ignore_autogenerated

/*
Copyright 2019 Kazumasa Kohtaka <kkohtaka@gmail.com>.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by embedtexts.go. DO NOT EDIT.

package %s

const (
`, packageName)))
	for i := range inputs {
		baseName := path.Base(inputs[i].Name())
		name := strcase.ToLowerCamel(path.Base(strings.Replace(baseName, ".", "_", -1)))
		content, err := ioutil.ReadFile(path.Join(inputDirName, baseName))
		if err != nil {
			log.Fatalf("Failed to read a file: %s, %v\n", inputs[i].Name(), err)
		}
		output.Write([]byte(fmt.Sprintf("	%s = `%s`\n", name, content)))
	}
	output.Write([]byte(`)
`))
}
