name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build a Docker image

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: bazel run //:push_kubernetesimal
