name: main

on:
  push: {}
  pull_request: {}

jobs:
  validate:
    name: Validate repository status

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel run //:gazelle-validate


  build:
    name: Run tests and build a Docker image

    needs:
      - validate

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: helm/kind-action@v1.3.0
      - run: bazel test //...
      - run: bazel build //:push_kubernetesimal


  publish:
    name: Publish a Docker image

    needs:
      - build

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: bazelbuild/setup-bazelisk@v2
      - uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: bazel run //:push_kubernetesimal
