name: test

on:
  push: {}
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run tests

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
          source <(setup-envtest use --print env)
          bazel test //...
