name: test

on:
  push: {}
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run tests

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: helm/kind-action@v1.2.0
      - run: bazel test //...
        env:
          USE_EXISTING_CLUSTER: 'true'
